#import libraries and reference the RevitAPI and RevitAPIUI
import clr
import math
clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
from Autodesk.Revit.DB import * 
 
#set the active Revit application and document
app = __revit__.Application
doc = __revit__.ActiveUIDocument.Document
#define a transaction variable and describe the transaction
t = Transaction(doc, 'This is my new transaction')
#start a transaction in the Revit database
t.Start()
 
#perform some action here...
print dir(uidoc)

print "All Walls:"
walls = FilteredElementCollector(doc).OfClass(Wall)
for elem in walls:
    print elem, elem.Id
print "--------------------------"
print "All Ceilings:"
ceilings = FilteredElementCollector(doc).OfClass(Ceiling)
for elem in ceilings:
    print elem, elem.Id
print "--------------------------"
print "All Floors:"
floors = FilteredElementCollector(doc).OfClass(Floor)
for elem in floors:
    print elem, elem.Id
print "--------------------------"

#print "All Floor Types:"
#floors = FilteredElementCollector(doc).OfClass(FloorType)
#for elem in floors:
#    print elem, elem.Id, elem.Family.Name
print "--------------------------"
 
#commit the transaction to the Revit database
#t.Commit()
 
#close the script window
#__window__.Close()



